networks:
  goodfood:
    driver: bridge
services:
  users-db:
    container_name: users-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prismagoodfood
      - POSTGRES_DB=users
    networks:
      - goodfood
    ports:
      - "5433:5432"

  restaurants-db:
    container_name: restaurants-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prismagoodfood
      - POSTGRES_DB=restaurants
    networks:
      - goodfood

  plats-db:
    container_name: plats-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prismagoodfood
      - POSTGRES_DB=plats
    networks:
      - goodfood

  commandes-db:
    container_name: commandes-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prismagoodfood
      - POSTGRES_DB=commandes
    networks:
      - goodfood

  users-api:
    stdin_open: true
    image: 'rg.fr-par.scw.cloud/goodfood/users-api:latest'
    build:
      context: 'users-api'
      dockerfile: Dockerfile
    container_name: users-api
    environment:
      - DATABASE_URL=postgresql://prisma:prismagoodfood@users-db:5432/users
    ports:
      - '3001:3000'
    networks:
      - goodfood
    depends_on:
      - users-db

  auth-api:
    stdin_open: true
    image: 'rg.fr-par.scw.cloud/goodfood/auth-api:latest'
    build:
      context: 'auth-api'
      dockerfile: Dockerfile
    container_name: auth-api
    environment:
      - URL_USER=http://users-api:3000
    ports:
      - '3002:3000'
    networks:
      - goodfood
    depends_on:
      - users-api

  restaurants-api:
    stdin_open: true
    image: 'rg.fr-par.scw.cloud/goodfood/restaurants-api:latest'
    environment:
      - DATABASE_URL=postgresql://prisma:prismagoodfood@restaurants-db:5432/restaurants
    build:
      context: 'restaurants-api'
      dockerfile: Dockerfile
    container_name: restaurants-api
    ports:
      - '3003:3000'
    networks:
      - goodfood
    depends_on:
      - restaurants-db

  plats-api:
    stdin_open: true
    image: 'rg.fr-par.scw.cloud/goodfood/plats-api:latest'
    build:
      context: 'plats-api'
      dockerfile: Dockerfile
    container_name: plats-api
    environment:
      - DATABASE_URL=postgresql://prisma:prismagoodfood@plats-db:5432/plats
    ports:
      - '3004:3000'
    networks:
      - goodfood
    depends_on:
      - plats-db

  commandes-api:
    stdin_open: true
    image: 'rg.fr-par.scw.cloud/goodfood/commandes-api:latest'
    build:
      context: 'commandes-api'
      dockerfile: Dockerfile
    container_name: commandes-api
    environment:
      - DATABASE_URL=postgresql://prisma:prismagoodfood@commandes-db:5432/commandes
    ports:
      - '3005:3000'
    networks:
      - goodfood
    depends_on:
      - commandes-db

  front-end:
    stdin_open: true
    image: 'rg.fr-par.scw.cloud/goodfood/front-end:latest'
    build:
      context: 'front-end'
      dockerfile: Dockerfile
    container_name: front-end
    ports:
      - '80:3000'
    networks:
      - goodfood
